### ISSUE TITLE
Please help me with the error that occurred.

### ISSUE THREAD

**Issue by fine4546** [zhongcl-thu/SNAKE#2]
"I am using conda with cuda 10.1, but I am getting an error that says 

'RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_scatter has CUDA version 10.1. Please reinstall the torch_scatter that matches your PyTorch install.' 

What should I do to resolve this error? Do I really need cuda 10.2?"

So I installed a cuda 10.2 environment using Docker, but I'm having trouble installing it due to a tensorflow-estimator version issue. How can I resolve this?
What's for sure is that Docker is not the solution to this problem.

**Comment by zhongcl-thu** [comment]
> 

You can download the appropriate version of torch_scatter that matches your PyTorch version from the PyTorch website at https://download.pytorch.org/whl/torch_stable.html. Once you have downloaded the correct version, you can uninstall the current version of torch_scatter and reinstall the new version.
